version: '3.4'

networks:
  hclarticleserviceapi_dev:
    external: true

services:
  hcl.identityserver.api:
    image: ${DOCKER_REGISTRY-}hclidentityserverapi
    depends_on: 
      - app_db_hcl_identity
    container_name: HCL.IdentityServer
    build:
      context: .
      dockerfile: HCL.IdentityServer.API/Dockerfile
    ports: 
      - "5001:5001"
    environment:
      ElasticConfiguration__Uri: http://elasticsearch:9200
      GRPC-SERVER-PORT: 5001
      ConnectionStrings__NpgConnectionString: User Id=postgres; Password=pg; Server=app_db_hcl_identity; Port=5432; Database=HCL_IdentityServer; IntegratedSecurity=true; Pooling=true;
      RedisOption__Host: host.docker.internal:6379,password=redis
    networks:
      - hclarticleserviceapi_dev

  cache:
    image: redis:latest
    container_name: hclredis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes: 
      - cache:/data

  app_db_hcl_identity: 
    image: postgres:latest
    container_name: app_db_hcl_identity
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=HCL_IdentityServer
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - hclarticleserviceapi_dev
            
volumes:
  app_data:
  cache: